# Generated by Django 4.0.4 on 2022-05-17 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_mentee_mentor_ranking_delete_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='rank',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
