# Generated by Django 4.0.4 on 2022-05-17 00:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_ranking_rank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='MenteeRanking',
        ),
        migrations.CreateModel(
            name='MentorRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.mentor')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.programme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
