# Generated by Django 4.0.4 on 2022-05-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_rename_ranking_menteeranking_mentorranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='programme.programme'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='programme.programme'),
        ),
    ]
