# Generated by Django 4.0.4 on 2022-05-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0008_alter_menteeranking_mentee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)s', to='programme.programme'),
        ),
        migrations.AlterField(
            model_name='menteeranking',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)s', to='programme.mentee'),
        ),
        migrations.AlterField(
            model_name='menteeranking',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)s', to='programme.mentor'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)s', to='programme.programme'),
        ),
        migrations.AlterField(
            model_name='mentorranking',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)s', to='programme.mentee'),
        ),
        migrations.AlterField(
            model_name='mentorranking',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)s', to='programme.mentor'),
        ),
    ]
